language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  yarn: true
before_script:
- yarn install
script:
- yarn test
deploy:
  provider: npm
  email: nicklas@skarp.dk
  api_key:
    secure: m38XMt8047TVN391joi4sApp3p+vDeohvEG4lzh25xBlRXZ/t+wf5rGr4z4Q1bBSwQdhds04yy6k+2RXl9B77WdOHNKVIA0WwvKc7caqnZofkz7ajo4rmliKAJj9kWi+pi5A8iVQRYU5souFywj4zzfUomDtSYy5heN+jJk0X+rjHPxusCo2x+Oot/xovOj2zurYFH8xvyNA3Cy5BdXcRN2MgIqPJzOfZ9+RjHhzdHDJWCDDKhoFBBMDmmAMCZmiBnNULLRJWPH7y6Kb35gSKQ6eQlXQkyG/b8nQV6fnLwMSpXXolbHh0ePm6Jf/6BQEXrAkgZ9C3EXtv4CrUz7Ubv0CXq5C27DSf37hP09/CE6olZGVcNBrX3z6JKsdq8wufo0OKAlCrIk4zzT1Jwe3Wi0HDJQU+qx4RehQzwXc6jeSvvGoiDbwyYyPdjx9CDyG0Iy9JWx7UAbbnJtiPGEfbw+9MZ2OTi+FLJP5hv1VCsC9Fs1ZnH5AczHQVoeZp8/FlmzbsR9kdiSUXfxSJO9Yfly8N/9ri1AGJPxK9gk35PaUTKCvjwzXA7xC2ikOCoSKLTg/Mem3NGuAIfELqoLjBmQUOHHSEwUOsWkCmDB3oRrb8wIG30OVnP2wmGgWuc6DTBI+FsW9OBdR2UodsRoNfehJpIWjiYTRueySTyxCzZU=
  on:
    tags: true
    repo: skarpdev/hapi-graphql-2
